server:
  port: ${ELSIE_DEE_PORT:80}
  context-path: /elsie-dee

spring:
  application:
    name: elsie-dee

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST_NAME:eureka-service}:${EUREKA_SERVICE_PORT:8083}/eureka/
    healthcheck:
      enabled: true

management:
  security:
    enabled: false

feign:
  compression:
    request:
      enabled: true
    mime-types: application/json, application/octet-stream, image/png
    response:
      enabled: true

elsie-deetect:
  ribbon:
    listOfServers: http://elsie-deetect:8080
  ConnectTimeout: 10000
  ReadTimeout: 60000

elsie-deesight:
  ribbon:
    listOfServers: http://elsie-deesight:8085
  ConnectTimeout: 10000
  ReadTimeout: 60000

ribbon:
  eureka:
   enabled: false

endpoints:
  refresh:
    enabled: true
  restart:
    enabled: true
