server:
  port: ${ELSIE_DEESIGHT_PORT:8085}
  context-path: /elsie-deesight

spring:
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST_NAME:eureka-service}:${EUREKA_SERVICE_PORT:8083}/eureka/
    healthcheck:
      enabled: true

management:
  security:
    enabled: false

feign:
  compression:
    request:
      enabled: true
    mime-types: application/json, image/png, video/mp4
    response:
      enabled: true

face-classifier:
  ribbon:
    listOfServers: http://face-classifier:8084
  ConnectTimeout: 10000
  ReadTimeout: 60000

ribbon:
  eureka:
   enabled: false

endpoints:
  refresh:
    enabled: true
  restart:
    enabled: true
