server:
  port: ${ELSIE_DEE_PORT:80}
  context-path: /elsie-dee

spring:
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST_NAME:eureka-service}:${EUREKA_SERVICE_PORT:8083}/eureka/
    healthcheck:
      enabled: true

management:
  security:
    enabled: false

feign:
  client:
    default:
      ConnectTimeout: 10000
      ReadTimeout: 60000
  compression:
    request:
      enabled: true
    mime-types: application/json, application/octet-stream, image/png, video/mp4, video/avi
    response:
      enabled: true

elsie-deetect:
  ribbon:
    listOfServers: http://elsie-deetect:8080
  ConnectTimeout: 10000
  ReadTimeout: 60000

elsie-deesight:
  ribbon:
    listOfServers: http://elsie-deesight:8085
  ConnectTimeout: 10000
  ReadTimeout: 60000

elsie-dee-audiorip:
  ribbon:
    listOfServers: http://elsie-dee-audiorip:8086
  ConnectTimeout: 10000
  ReadTimeout: 60000

elsie-dee-search:
  ribbon:
    listOfServers: http://elsie-dee-search:8087
  ConnectTimeout: 10000
  ReadTimeout: 60000

stream-services:
  ribbon:
    listOfServers: http://stream-services:8088
  ConnectTimeout: 60000
  ReadTimeout: 100000

ribbon:
  eureka:
   enabled: false

endpoints:
  refresh:
    enabled: true
  restart:
    enabled: true
