server:
  port: 8085
  context-path: /elsie-deesight

spring:
  application:
    name: elsie-deesight

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ADVERTISED_HOST_NAME:eureka-service}:8083/eureka/
    healthcheck:
      enabled: true

management:
  security:
    enabled: false

feign:
  compression:
    request:
      enabled: true
    mime-types: application/json,image/png
    response:
      enabled: true

face-classifier:
  ribbon:
    listOfServers: http://face-classifier:8084
  ConnectTimeout: 10000
  ReadTimeout: 60000

ribbon:
  eureka:
   enabled: false

endpoints:
  refresh:
    enabled: true
  restart:
    enabled: true
