server:
  port: ${ELSIE_DEE_SEARCH_PORT:8087}
  context-path: /elsie-dee-search

spring:
  data:
    elasticsearch:
      cluster-name: elastic-cluster
      cluster-nodes: elasticsearch:9300

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST_NAME:eureka-service}:${EUREKA_SERVICE_PORT:8083}/eureka/
    healthcheck:
      enabled: true

management:
  security:
    enabled: false

endpoints:
  refresh:
    enabled: true
  restart:
    enabled: true
